org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true

# Fix for multi-drive Windows Kotlin incremental compiler cross-drive root bug (C: vs D:)
kotlin.incremental=false
kotlin.incremental.android=false
kotlin.incremental.jvm=false
kotlin.incremental.js=false
kapt.incremental.apt=false
